// <auto-generated />
using System;
using CustomerAiAgent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerAiAgent.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerAiAgent.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 rue de Paris, 75001 Paris",
                            Email = "jean.dupont@example.com",
                            FirstName = "Jean",
                            LastName = "Dupont"
                        },
                        new
                        {
                            Id = 2,
                            Address = "25 avenue Victor Hugo, 75016 Paris",
                            Email = "sophie.martin@example.com",
                            FirstName = "Sophie",
                            LastName = "Martin"
                        },
                        new
                        {
                            Id = 3,
                            Address = "8 rue Nationale, 69001 Lyon",
                            Email = "thomas.bernard@example.com",
                            FirstName = "Thomas",
                            LastName = "Bernard"
                        },
                        new
                        {
                            Id = 4,
                            Address = "15 rue de la République, 69002 Lyon",
                            Email = "claire.petit@example.com",
                            FirstName = "Claire",
                            LastName = "Petit"
                        },
                        new
                        {
                            Id = 5,
                            Address = "42 boulevard Haussmann, 75009 Paris",
                            Email = "nicolas.robert@example.com",
                            FirstName = "Nicolas",
                            LastName = "Robert"
                        },
                        new
                        {
                            Id = 6,
                            Address = "18 rue de Lille, 59000 Lille",
                            Email = "julie.richard@example.com",
                            FirstName = "Julie",
                            LastName = "Richard"
                        },
                        new
                        {
                            Id = 7,
                            Address = "7 rue des Écoles, 33000 Bordeaux",
                            Email = "alexandre.moreau@example.com",
                            FirstName = "Alexandre",
                            LastName = "Moreau"
                        },
                        new
                        {
                            Id = 8,
                            Address = "31 avenue Jean Jaurès, 31000 Toulouse",
                            Email = "camille.simon@example.com",
                            FirstName = "Camille",
                            LastName = "Simon"
                        },
                        new
                        {
                            Id = 9,
                            Address = "22 rue Nationale, 44000 Nantes",
                            Email = "laurent.michel@example.com",
                            FirstName = "Laurent",
                            LastName = "Michel"
                        },
                        new
                        {
                            Id = 10,
                            Address = "5 rue Victor Hugo, 67000 Strasbourg",
                            Email = "emma.leroy@example.com",
                            FirstName = "Emma",
                            LastName = "Leroy"
                        });
                });

            modelBuilder.Entity("CustomerAiAgent.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 149.99m,
                            CustomerId = 1,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 299.90m,
                            CustomerId = 1,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 89.50m,
                            CustomerId = 1,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 459.00m,
                            CustomerId = 1,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 79.90m,
                            CustomerId = 2,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 199.99m,
                            CustomerId = 2,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 349.00m,
                            CustomerId = 2,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 120.00m,
                            CustomerId = 3,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 580.50m,
                            CustomerId = 3,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 59.90m,
                            CustomerId = 4,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 129.90m,
                            CustomerId = 4,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 249.00m,
                            CustomerId = 4,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 399.99m,
                            CustomerId = 4,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 89.99m,
                            CustomerId = 4,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 199.00m,
                            CustomerId = 5,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 450.00m,
                            CustomerId = 5,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 75.50m,
                            CustomerId = 6,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 299.99m,
                            CustomerId = 6,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 159.90m,
                            CustomerId = 6,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 99.99m,
                            CustomerId = 8,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 21,
                            Amount = 249.90m,
                            CustomerId = 8,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 22,
                            Amount = 599.00m,
                            CustomerId = 8,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 23,
                            Amount = 129.00m,
                            CustomerId = 8,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 24,
                            Amount = 349.99m,
                            CustomerId = 9,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 25,
                            Amount = 799.00m,
                            CustomerId = 9,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = 26,
                            Amount = 129.90m,
                            CustomerId = 9,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 27,
                            Amount = 69.99m,
                            CustomerId = 10,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 28,
                            Amount = 299.99m,
                            CustomerId = 10,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered"
                        });
                });

            modelBuilder.Entity("CustomerAiAgent.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 349.99m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 3,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 4,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 899.99m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 5,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 49.99m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 6,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 159.99m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 7,
                            ProductId = 7,
                            Quantity = 2,
                            UnitPrice = 119.99m
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 8,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 69.99m
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 9,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 899.99m
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 10,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 11,
                            OrderId = 11,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 12,
                            OrderId = 12,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 349.99m
                        },
                        new
                        {
                            Id = 13,
                            OrderId = 13,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 899.99m
                        },
                        new
                        {
                            Id = 14,
                            OrderId = 14,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 15,
                            OrderId = 15,
                            ProductId = 10,
                            Quantity = 2,
                            UnitPrice = 79.99m
                        },
                        new
                        {
                            Id = 16,
                            OrderId = 16,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 159.99m
                        },
                        new
                        {
                            Id = 17,
                            OrderId = 17,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 69.99m
                        },
                        new
                        {
                            Id = 18,
                            OrderId = 18,
                            ProductId = 7,
                            Quantity = 2,
                            UnitPrice = 119.99m
                        },
                        new
                        {
                            Id = 19,
                            OrderId = 19,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 49.99m
                        },
                        new
                        {
                            Id = 20,
                            OrderId = 20,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 21,
                            OrderId = 21,
                            ProductId = 5,
                            Quantity = 2,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 22,
                            OrderId = 22,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 899.99m
                        },
                        new
                        {
                            Id = 23,
                            OrderId = 23,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 24,
                            OrderId = 24,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 349.99m
                        },
                        new
                        {
                            Id = 25,
                            OrderId = 25,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 899.99m
                        },
                        new
                        {
                            Id = 26,
                            OrderId = 26,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 119.99m
                        },
                        new
                        {
                            Id = 27,
                            OrderId = 27,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 79.99m
                        },
                        new
                        {
                            Id = 28,
                            OrderId = 28,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 159.99m
                        });
                });

            modelBuilder.Entity("CustomerAiAgent.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ordinateur portable professionnel 15 pouces",
                            IsActive = true,
                            Name = "Ordinateur portable Dell",
                            Price = 899.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 2,
                            Description = "Écran professionnel QHD 27 pouces",
                            IsActive = true,
                            Name = "Écran Dell 27 pouces",
                            Price = 349.99m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 3,
                            Description = "Clavier mécanique USB avec rétroéclairage",
                            IsActive = true,
                            Name = "Clavier mécanique",
                            Price = 89.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 4,
                            Description = "Souris ergonomique sans fil",
                            IsActive = true,
                            Name = "Souris sans fil",
                            Price = 49.99m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 5,
                            Description = "Casque audio Bluetooth avec réduction de bruit",
                            IsActive = true,
                            Name = "Casque Bluetooth",
                            Price = 129.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 6,
                            Description = "Station d'accueil USB-C multi-écrans",
                            IsActive = true,
                            Name = "Station d'accueil USB-C",
                            Price = 159.99m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 7,
                            Description = "Disque SSD externe USB 3.2 de 1 To",
                            IsActive = true,
                            Name = "SSD externe 1 To",
                            Price = 119.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 8,
                            Description = "Webcam Full HD pour visioconférence",
                            IsActive = true,
                            Name = "Webcam Full HD",
                            Price = 69.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 9,
                            Description = "Sacoche professionnelle pour ordinateur 15 pouces",
                            IsActive = true,
                            Name = "Sacoche ordinateur",
                            Price = 59.99m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 10,
                            Description = "Chargeur rapide USB-C 100W",
                            IsActive = true,
                            Name = "Chargeur USB-C 100W",
                            Price = 79.99m,
                            Stock = 60
                        });
                });

            modelBuilder.Entity("CustomerAiAgent.Domain.Entities.Order", b =>
                {
                    b.HasOne("CustomerAiAgent.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CustomerAiAgent.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("CustomerAiAgent.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerAiAgent.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CustomerAiAgent.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CustomerAiAgent.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
